---
title: Session 3
subtitle: Reproducibility and Collaboration (Version Control, Quarto)
date: 2025-12
---


Tools for reproducible science (environments, git, dvc, data formats) and collaboration (quarto, github)


### Codes: environments

Conda/Mamba/Pixi, pip/uv, Docker


### Data: formats

csv, json/yaml, parquet

BDM, BIDS, Psych-DS, FAIR principles


### Version Control for Reproducibility

Git, DVC

#### Git

- Install git (if not installed)
- Create a github account (if you don't have one)
- Create a new repository on GitHub (e.g., "my-first-repo")
- Clone the repository to your local machine:

```bash
    git clone
    cd my-first-repo
```

- Create a new file (e.g., `README.md`) and add some content to it.
- Save the changes with a descriptive message:
```bash
    git commit -am "Add README file"
```
- Upload the changes to GitHub:
```bash
    git push origin main
```
- Make further changes to the file or add new files, then repeat the commit and push steps to update your repository.


#### Data Version Control (DVC)

Git helps manage software code. But data version control, managing changes to datasets and models, is not so easy.

DVC is an open-source tool that helps govern data and models. It works on top of Git, tracking changes to large files, datasets, and machine learning models without storing them directly in your Git repository. Alternatives include Git LFS, LakeFS, datachain, DataLad/git-annex, etc.

> Some terms: database, dataset, data registry/catalog, data warehouse, etc, lineage, provenance, reproducibility, immutability, checksum, remote storage

#### Basic DVC workflow

0. `dvc init` - Initialize DVC in your project
1. `dvc config core.analytics false` - Disable analytics if desired
2. `dvc add <data-file>` - Track a data file with DVC
3. `git add <data-file>.dvc .gitignore` - Stage DVC
4. `git commit -m "Add data file"` - Commit changes to Git
5. `dvc remote add -d myremote <remote-storage-url>` - Add remote
6. `dvc push` - Push data to remote storage
7. `dvc pull` - Pull data from remote storage
8. `dvc repro` - Reproduce the pipeline

#### DVC remote storage options

- Local filesystem
- SSH (e.g., HPC clusters)
- Cloud storage (AWS S3, Google Cloud Storage, Azure Blob Storage)
- etc


### Version Control for Collaboration

Git/Hub, branching, pull requests, merging, issues

- fork repositories, create branches, and submit pull requests on GitHub.
- Use issues to track tasks, enhancements, and bugs.
- Review code changes before merging.
- Use GitHub Projects for project management.

### Publishing and Sharing

Markdown, Quarto, GitHub Pages, Zenodo, OSF
